# Generated by Django 4.1 on 2022-11-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ('name',)},
        ),
    ]
