# Generated by Django 4.1 on 2022-11-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_space_members_alter_space_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
