# Generated by Django 4.1 on 2022-11-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_space_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacemember',
            old_name='roles',
            new_name='groups',
        ),
    ]
