# Generated by Django 4.1 on 2022-11-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='created_by',
            new_name='owner',
        ),
    ]
