# Generated by Django 4.1 on 2022-11-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_rename_created_by_issue_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
    ]
