# Generated by Django 4.1 on 2022-11-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_updated_issuecomment_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('updated',)},
        ),
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'ordering': ('updated',)},
        ),
    ]
