# Generated by Django 4.1 on 2022-11-12 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0007_alter_issue_options_alter_issuecomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='mentioned_comments',
            field=models.ManyToManyField(to='issues.issuecomment'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='mentioned_issues',
            field=models.ManyToManyField(related_name='mentioned_in', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='mentioned_users',
            field=models.ManyToManyField(related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
