# Generated by Django 4.1 on 2022-11-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issuelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelabel',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='labels', to='issues.issue'),
        ),
    ]
