# Generated by Django 4.1 on 2022-11-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_alter_issuelabel_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelabel',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
