# Generated by Django 4.1 on 2022-11-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_alter_issuelabel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuelabel',
            options={'ordering': ('name',)},
        ),
    ]
