# Generated by Django 4.1 on 2022-11-26 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
        ('issues', '0014_alter_issuelabel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_issues', to='spaces.space'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
