# Generated by Django 4.1 on 2022-11-26 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_space_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0015_issue_space_alter_issue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='spaces.space'),
        ),
    ]
